### PR TITLE
[ADD] 2024.03.08 - 论文阅读：CDN 转发请求不一致导致的 DoS 攻击

### PR DESCRIPTION
**Pull request by tarihub**

### CODE REVIEW

**Comment by ssst0n3** [comment]
@tarihub 
这是今年的论文吗，我怎么记得以前就听过这种打法

**Comment by ssst0n3** [comment]
哦，他是提出测试方法？

**Comment by tarihub** [comment]
> Member

是新的，2月份的 https://www.ndss-symposium.org/ndss-paper/reqsminer-automated-discovery-of-cdn-forwarding-request-inconsistencies-and-dos-attacks-with-grammar-based-fuzzing/

> By extension, our work further identifies three novel types of HTTP amplification DoS attacks and uncovers 74 new potential DoS vulnerabilities with an amplification factor that can reach up to 2,000 generally, and even 1,920,000 under specific conditions

清华那边做的

**Comment by tarihub** [comment]
image

**Comment by ssst0n3** [comment]
哦哦，我应该是他们给厂商报告的时候听说的

**Review by ssst0n3 — APPROVED** [review]

**Comment by ssst0n3** [comment]
牛啊

**Pull request merged**
